styles:
    inputs:
        - 'bundles/oroui/default/scss/settings/global-settings.scss'
    output: 'css/styles.css'

stylebook_styles:
    inputs:
        - 'bundles/oroui/default/scss/settings/global-settings.scss'

print_styles:
    inputs:
        - 'bundles/oroui/default/scss/settings/global-settings.scss'
    output: 'css/styles-print.css'
    auto_rtl_inputs:
        - 'bundles/oro*/**'

