# @see \Oro\Component\Testing\Doctrine\PersistentConnection::getConnectionId
doctrine:
  dbal:
    connections:
      default:
        options: { ConnectionId: default }
      config:
        options: { ConnectionId: config }
      message_queue:
        options: { ConnectionId: message_queue }
      search:
        options: { ConnectionId: search }

oro_test_framework:
  install_options:
    user_name: admin
    user_email: admin@example.com
    user_firstname: John
    user_lastname: Doe
    user_password: admin
    sample_data: false
    organization_name: OroInc
    application_url: http://localhost/
    skip_translations: true
    timeout: 600
    language: en
    formatting_code: en_US

oro_layout:
  enabled_themes:
    - default
    - custom
    - custom_standalone

oro_entity_extend:
  custom_entities:
    - Extend\Entity\TestEntity1
    - Extend\Entity\TestEntity2
    - Extend\Entity\TestEntity3
    - Extend\Entity\TestEntity4
    - Extend\Entity\TestEntity5
