services:
    _defaults:
        public: true

    Oro\Bundle\ApiBundle\Controller\RestApiController:
        arguments:
            - '@oro_api.rest.request_handler'

    Oro\Bundle\ApiBundle\Controller\RestApiDocController:
        arguments:
            - '@nelmio_api_doc.extractor.api_doc_extractor'
            - '@nelmio_api_doc.formatter.html_formatter'
            - '@request_stack'

    Oro\Bundle\ApiBundle\Controller\OpenApiSpecificationController:
        arguments:
            - '@form.factory'
            - '@oro_form.update_handler'
            - '@oro_entity.delete_handler_registry'
            - '@translator'
            - '@doctrine'
            - '@oro_message_queue.client.message_producer'

    Oro\Bundle\ApiBundle\Controller\DownloadOpenApiSpecificationController:
        arguments:
            - '@oro_api.open_api_specification_archive'

    Oro\Bundle\ApiBundle\Controller\DownloadPublicOpenApiSpecificationController:
        arguments:
            - '@doctrine'
            - '@oro_api.open_api_specification_archive'
            - 0 # preflightMaxAge. It is set by Oro\Bundle\ApiBundle\DependencyInjection\Compiler\OpenApiCompilerPass
            - [] # allowedOrigins. They are set by Oro\Bundle\ApiBundle\DependencyInjection\Compiler\OpenApiCompilerPass
            - [] # allowedHeaders. They are set by Oro\Bundle\ApiBundle\DependencyInjection\Compiler\OpenApiCompilerPass
