services:
    oro_workflow.validator.transition_is_allowed:
        class: Oro\Bundle\WorkflowBundle\Validator\Constraints\TransitionIsAllowedValidator
        arguments:
            - '@oro_workflow.registry'
        tags:
            - { name: validator.constraint_validator }

    oro_workflow.validator.workflow_entity:
        class: Oro\Bundle\WorkflowBundle\Validator\Constraints\WorkflowEntityValidator
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@oro_workflow.permission_registry'
            - '@oro_workflow.restriction.manager'
            - '@oro_entity.helper.field_helper'
            - '@property_accessor'
        tags:
            - { name: validator.constraint_validator }
