services:
    oro_entity_extend.entity_metadata_builder:
        class: Oro\Bundle\EntityExtendBundle\ORM\ExtendMetadataBuilder
        arguments:
            - '@oro_entity_config.provider.extend'
            - !tagged_iterator oro_entity_extend.entity_metadata_builder

    oro_entity_extend.entity_metadata_builder.relations:
        class: Oro\Bundle\EntityExtendBundle\ORM\RelationMetadataBuilder
        arguments:
            - '@oro_entity_config.config_manager'
            - '@oro_entity_extend.db_id_name_generator'
            - '@Doctrine\Inflector\Inflector'
        tags:
            - { name: oro_entity_extend.entity_metadata_builder, priority: 10 }

    oro_entity_extend.entity_metadata_builder.indices:
        class: Oro\Bundle\EntityExtendBundle\ORM\IndexMetadataBuilder
        arguments:
            - '@oro_entity_config.provider.extend'
            - '@oro_entity_extend.db_id_name_generator'
        tags:
            - { name: oro_entity_extend.entity_metadata_builder, priority: 20 }

    oro_entity_extend.listener.entity_listener:
        class: Oro\Bundle\EntityExtendBundle\EventListener\DoctrineListener
        arguments:
            - '@oro_entity_extend.entity_metadata_builder'
            - '@oro_platform.attribute_reader'
            - '@oro_entity_config.provider.extend'
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
