services:
    oro_wsse_authentication.security.core.authentication.authenticator.wsse:
        class:  Oro\Bundle\WsseAuthenticationBundle\Security\Core\Authentication\WsseAuthenticator
        abstract: true
        arguments:
            - '%kernel.environment%'
            - '@oro_api.security.authenticator.feature_checker'
            - '@security.token_storage'
            - '@oro_wsse_authentication.security.wsse_token_factory'
            - '<UserProviderInterface $userProvider>' # set in WsseSecurityAuthenticatorFactory
            - '<AuthenticationEntryPointInterface $authenticationEntryPoint>' # set in WsseSecurityAuthenticatorFactory
            - '<string $firewallName>' # set in WsseSecurityAuthenticatorFactory
            - '<PasswordEncoderInterface $encoder>' # set in WsseSecurityAuthenticatorFactory
            - '<CacheInterface $nonceCache>' # set in WsseSecurityAuthenticatorFactory
            - 300
            - '@security.firewall.map'
            - '@oro_featuretoggle.checker.feature_checker'

    oro_wsse_authentication.security.http.entry_point.wsse:
        class:  Oro\Bundle\WsseAuthenticationBundle\Security\Http\EntryPoint\WsseEntryPoint
        abstract: true
        arguments:
            - '%kernel.environment%'
            - '@?logger'
            - ''
            - 'UsernameToken'

    oro_wsse_authentication.hasher:
        class: Symfony\Component\PasswordHasher\Hasher\MessageDigestPasswordHasher
        arguments:
            - 'sha1'
            - true
            - 1

    oro_wsse_authentication.nonce_cache:
        class: Symfony\Component\Cache\Adapter\PhpFilesAdapter
        abstract: true
        arguments:
            - '<namespace>' # set in WsseNonceCachePass
            - '<lifetime>' # set in WsseNonceCachePass
            - '%kernel.cache_dir%/security/nonces'

    oro_wsse_authentication.security.wsse_token_factory:
        class: Oro\Bundle\WsseAuthenticationBundle\Security\WsseTokenFactory

    oro_wsse_authentication.security.wsse_login_source_provider:
        class: Oro\Bundle\WsseAuthenticationBundle\Security\WsseLoginSourceProvider
        tags:
            - { name: oro_security.login_source_provider.fail }

    oro_wsse_authentication.event_listener.authentication:
        class: Oro\Bundle\WsseAuthenticationBundle\EventListener\AuthenticationListener
        arguments:
            - "@oro_user.logger.user_login_attempt"
        tags:
            - { name: kernel.event_listener, event: security.authentication.success, method: onAuthenticationSuccess }
