charts:
    line_chart:
        label: oro.chart.line_chart.label
        data_schema:
          - name: label
            label: oro.chart.line_chart.params.label
            required: true
            default_type: string
          - name: value
            label: oro.chart.line_chart.params.value
            required: true
            type_filter: [percent, number, numberDecimal] # filter for fields, see query_designer.yml filter section
            default_type: decimal
        default_settings:
            connect_dots_with_line: true
            available_in_reports: true
            chartColors: ['#B5D8DA', '#E6CFE3', '#CEDFF6', '#EFD7A7', '#CAB0B0', '#A2B4D2', '#BDD4B3', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: '@OroChart/Chart/line.html.twig'
    multiline_chart:
        label: oro.chart.multiline_chart.label
        data_schema:
          - name: label
            label: oro.chart.multiline_chart.params.label
            required: true
            default_type: string
          - name: value
            label: oro.chart.multiline_chart.params.value
            required: true
            type_filter: [percent, number] # filter for fields, see query_designer.yml filter section
            default_type: decimal
        default_settings:
            connect_dots_with_line: true
            chartColors: ['#B5D8DA', '#E6CFE3', '#CEDFF6', '#EFD7A7', '#CAB0B0', '#A2B4D2', '#BDD4B3', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: '@OroChart/Chart/multiline.html.twig'
    bar_chart:
        label: oro.chart.bar_chart.label
        data_schema:
          - name: label
            label: oro.chart.bar_chart.params.label
            required: true
            default_type: string
          - name: value
            label: oro.chart.bar_chart.params.value
            required: true
            type_filter: [percent, number] # filter for fields, see query_designer.yml filter section
            default_type: decimal
        default_settings:
            chartColors: ['#B5D8DA', '#E6CFE3', '#CEDFF6', '#EFD7A7', '#CAB0B0', '#A2B4D2', '#BDD4B3', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: '@OroChart/Chart/bar.html.twig'
    horizontal_bar_chart:
        label: oro.chart.bar_chart.label
        data_schema:
          - name: label
            label: oro.chart.bar_chart.params.label
            required: true
            default_type: string
          - name: value
            label: oro.chart.bar_chart.params.value
            required: true
            type_filter: [percent, number] # filter for fields, see query_designer.yml filter section
            default_type: decimal
        default_settings:
            chartColors: ['#B5D8DA', '#E6CFE3', '#CEDFF6', '#EFD7A7', '#CAB0B0', '#A2B4D2', '#BDD4B3', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: '@OroChart/Chart/horizontal_bar.html.twig'
    stackedbar_chart:
        label: oro.chart.bar_chart.label
        data_schema:
          - name: label
            label: oro.chart.bar_chart.params.label
            required: true
            default_type: string
          - name: value
            label: oro.chart.bar_chart.params.value
            required: true
            type_filter: [percent, number] # filter for fields, see query_designer.yml filter section
            default_type: decimal
        default_settings:
            chartColors: ['#B5D8DA', '#E6CFE3', '#CEDFF6', '#EFD7A7', '#CAB0B0', '#A2B4D2', '#BDD4B3', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: '@OroChart/Chart/stackedbar.html.twig'
    pie_chart:
        label: oro.chart.pie_chart.label
        data_schema:
          - name: label
            label: oro.chart.pie_chart.params.label
            required: true
            default_type: string
          - name: value
            label: oro.chart.pie_chart.params.value
            required: true
            type_filter: [percent, number] # filter for fields, see query_designer.yml filter section
            default_type: decimal
        default_settings:
            fraction_input_data_field: value
            fraction_output_data_field: fraction
            chartColors: ['#B5D8DA', '#E6CFE3', '#CEDFF6', '#EFD7A7', '#CAB0B0', '#A2B4D2', '#BDD4B3', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        data_transformer: oro_chart.data_transformer.pie_chart
        template: '@OroChart/Chart/pie.html.twig'
    flow_chart:
        label: oro.chart.flow_chart.label
        data_schema:
          - name: label
            label: oro.chart.flow_chart.params.label
            required: true
            default_type: string
          - name: value
            label: oro.chart.flow_chart.params.value
            required: true
            type_filter: [percent, number] # filter for fields, see query_designer.yml filter section
            default_type: currency
          - name: isNozzle
            label: oro.chart.flow_chart.params.is_nozzle
            required: false
            default_type: boolean
            type_filter: [boolean] # filter for fields, see query_designer.yml filter section
        default_settings:
            chartColors: ['#B5D8DA', '#E6CFE3', '#CEDFF6', '#EFD7A7', '#CAB0B0', '#A2B4D2', '#BDD4B3', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: '@OroChart/Chart/flow.html.twig'
    overlaid_multiline_chart:
        label: oro.chart.overlaid_multiline_chart.label
        data_schema:
            - name: label
              label: oro.chart.overlaid_multiline_chart.params.label
              required: true
              default_type: string
            - name: value
              label: oro.chart.overlaid_multiline_chart.params.value
              required: true
              type_filter: [percent, number] # filter for fields, see query_designer.yml filter section
              default_type: decimal
        default_settings:
            connect_dots_with_line: true
            chartColors: ['#B5D8DA', '#E6CFE3', '#CEDFF6', '#EFD7A7', '#CAB0B0', '#A2B4D2', '#BDD4B3', '#8985C2', '#ECB574', '#84A377']
            chartFontSize: 9
            chartFontColor: '#454545'
            chartHighlightColor: '#FF5E5E'
        template: '@OroChart/Chart/multiline.html.twig'
        data_transformer: oro_chart.data_transformer.overlaid_multi_set
